[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
urls = { Repository = "https://github.com/Starry-OvO/aiotieba/", Documentation = "https://v-8.top/" }
name = "aiotieba"
description = "Asynchronous I/O Client/Reviewer for Baidu Tieba"
readme = "README.md"
requires-python = ">=3.9"
authors = [{ name = "Starry-OvO", email = "starry.qvq@gmail.com" }]
keywords = ["tieba", "crawler", "spider"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: AsyncIO",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: The Unlicense (Unlicense)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Internet :: WWW/HTTP :: Session",
]
dependencies = [
    "httpx>=0.23.0",
    "httpx_ws>=0.2.2",
    "aiomysql>=0.1.0",
    "beautifulsoup4>=4.0.0",
    "lxml>=4.0.0",
    "protobuf>=4.12.0",
    "pycryptodome>=3.0.0",
    "tomli>=2.0.0;python_version<'3.11'",
    "pysimdjson>=5.0.0,<5.1.0",
    "opencv-contrib-python-headless>=4.6.0.66"
]
dynamic = ["version"]

[tool.setuptools.packages.find]
include = ["aiotieba*"]

[tool.setuptools.package-data]
"aiotieba.config_example" = ["*.toml"]

[tool.setuptools.dynamic]
version = { attr = "aiotieba.__version__" }

[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py39', 'py310']
include = '\.pyi?$'

[tool.pytest.ini_options]
minversion = "6.0"
required_plugins = "pytest-asyncio"
addopts = "-q"
asyncio_mode = "strict"
